CREATE TABLE `DF_ACCOUNT_T` (
`ACCOUNT_ID` varchar(30) NOT NULL COMMENT '主键',
`USERNAME` varchar(20) NOT NULL COMMENT '用户名',
`PASSWORD` varchar(20) NOT NULL COMMENT '密码',
PRIMARY KEY (`ACCOUNT_ID`) 
)
COMMENT='用户登录表';

CREATE TABLE `DF_MENU_T` (
`MENU_ID` varchar(10) NOT NULL COMMENT '主键',
`MENU_NAME` varchar(10) NOT NULL COMMENT '菜单名称',
`PRIORITY` int NOT NULL COMMENT '菜单优先级，用于菜单排序',
PRIMARY KEY (`MENU_ID`) 
)
COMMENT='菜单表';

CREATE TABLE `DF_ARTICLE_T` (
`ARTICLE_ID` varchar(50) NOT NULL COMMENT '主键',
`ARTICLE_NAME` varchar(50) NOT NULL COMMENT '文章名称',
`AUTHOR` varchar(20) NOT NULL COMMENT '作者',
`CONTENT` mediumtext NOT NULL COMMENT '文章内容',
`IS_PUBLISHED` char(1) NOT NULL DEFAULT 'N' COMMENT '是否已发布，Y/N',
`CREATED_BY` varchar(20) NULL COMMENT '创建人',
`CREATE_DATE` date NULL COMMENT '创建时间',
`UPDATED_BY` varchar(20) NULL COMMENT '更新人',
`UPDATE_DATE` date NULL COMMENT '更新时间',
PRIMARY KEY (`ARTICLE_ID`) ,
INDEX `ARTICLE_NAME_INDEX` (`ARTICLE_NAME`),
INDEX `AUTHOR_INDEX` (`AUTHOR`)
)
COMMENT='文章表';

CREATE TABLE `DF_TOPIC_T` (
`TOPIC_ID` varchar(10) NOT NULL COMMENT '主键',
`TOPIC_NAME` varchar(50) NOT NULL COMMENT '主题名称',
PRIMARY KEY (`TOPIC_ID`) 
)
COMMENT='主题表';

CREATE TABLE `DF_ARTICLE_TOPIC_T` (
`ARTICLE_TOPIC_ID` varchar(50) NOT NULL COMMENT '主键',
`ARTICLE_ID` varchar(50) NOT NULL,
`TOPIC_ID` varchar(10) NOT NULL,
PRIMARY KEY (`ARTICLE_TOPIC_ID`) 
)
COMMENT='文章主题关联表';

CREATE TABLE `DF_CUSTOMER_T` (
`CUSTOMER_ID` varchar(10) NOT NULL COMMENT '主键',
`CUSTOMER_NO` varchar(20) NOT NULL COMMENT '用户编号（微信号)',
PRIMARY KEY (`CUSTOMER_ID`) 
)
COMMENT='app用户表';

CREATE TABLE `DF_COLLECTION_ID` (
`COLLECTION_ID` varchar(20) NOT NULL COMMENT '主键',
`CUSTOMER_ID` varchar(10) NOT NULL COMMENT 'app用户id',
`ARTICLE_ID` varchar(50) NOT NULL COMMENT '文章id',
PRIMARY KEY (`COLLECTION_ID`) 
)
COMMENT='收藏表';

CREATE TABLE `DF_EVALUATE_T` (
`EVALUATE_ID` varchar(10) NOT NULL COMMENT '主键',
`ARTICLE_ID` varchar(50) NOT NULL COMMENT '关联文章编号',
`CUSTOMER_ID` varchar(10) NOT NULL COMMENT '关联app用户id',
PRIMARY KEY (`EVALUATE_ID`) ,
UNIQUE INDEX `UK_CUSTOMER_ID` (`CUSTOMER_ID`)
)
COMMENT='点赞表';


ALTER TABLE `DF_ARTICLE_TOPIC_T` ADD CONSTRAINT `FK_ARTICLE_ID` FOREIGN KEY (`ARTICLE_ID`) REFERENCES `DF_ARTICLE_T` (`ARTICLE_ID`);
ALTER TABLE `DF_ARTICLE_TOPIC_T` ADD CONSTRAINT `FK_TOPIC_ID` FOREIGN KEY (`TOPIC_ID`) REFERENCES `DF_TOPIC_T` (`TOPIC_ID`);
ALTER TABLE `DF_COLLECTION_ID` ADD CONSTRAINT `FK_COLLECTION_ARTICLE_ID` FOREIGN KEY (`ARTICLE_ID`) REFERENCES `DF_ARTICLE_T` (`ARTICLE_ID`);
ALTER TABLE `DF_COLLECTION_ID` ADD CONSTRAINT `FK_COLLECTION_CUSTOMER_ID` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `DF_CUSTOMER_T` (`CUSTOMER_ID`);
ALTER TABLE `DF_EVALUATE_T` ADD CONSTRAINT `FK_EVALUATE_ARTICLE_ID` FOREIGN KEY (`ARTICLE_ID`) REFERENCES `DF_ARTICLE_T` (`ARTICLE_ID`);
ALTER TABLE `DF_EVALUATE_T` ADD CONSTRAINT `FK_EVALUATE_CUSTOMER_ID` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `DF_CUSTOMER_T` (`CUSTOMER_ID`);

